# Site settings
title: "Load Impact Documentation"
email: support@loadimpact.com
description: > # this means to ignore newlines until "baseurl:"
  The documentation site for Load Impact, the developer-centric load testing service.

url: "http://localhost:4040" # the base hostname & protocol for your site
baseurl: "/docs" # the subpath of your site, e.g. /docs
gh_url: "https://github.com/loadimpact/loadimpact-docs"

markdown: kramdown
kramdown:
  input: GFM

liquid:
  error_mode: strict

collections:
  v3:
    name: "3.0 (Lua) Docs"
    site_section: true
    output: true
    permalink: /3.0/:path/
    prefix: "/3.0"
    selectorName: "3.0"
    description: "Documentation for Load Impact 3.0, our completely web based product with scirting in Lua, in operation since 2011. As of Feb 1 2019, v3.0 is not available to new users. This documentation is provided for existing users."
    order: 1
  v4:
    name: "4.0 (k6/JS) Docs"
    site_section: true
    output: true
    permalink: /4.0/:path/
    prefix: "/4.0"
    selectorName: "4.0"
    description: "Documentation for Load Impact 4.0. Launched during the Summer of 2018. Write test scripts in JavaScript, execute tests within the web interface or trigger cloud or local tests from the command line with k6."
    order: 0
  # api:
  #   name: "API Docs"
  #   site_section: true
  #   output: true
  #   permalink: /api/:path/
  #   prefix: "/api"
  #   selectorName: "API"
  #   description: "Reference for the Load Impact API."
  #   order: 2

sass:
  sass_dir: _sass

highlighter: rouge

twitter_username: loadimpact
github_username: loadimpact

defaults:
  -
    scope:
      path: ""
    values:
      hide: false
      search: true

algolia:
  application_id: OW2UD9NPMI
  index_name: staging_li_docs

plugins:
  - jekyll-redirect-from
