# Site settings
title: "Load Impact Documentation"
email: support@loadimpact.com
description: > # this means to ignore newlines until "baseurl:"
  The documentation site for Load Impact, the developer-centric load testing service.

url: "http://localhost:4040" # the base hostname & protocol for your site
baseurl: "/docs" # the subpath of your site, e.g. /docs
gh_url: "https://github.com/loadimpact/loadimpact-docs"

markdown: kramdown
kramdown:
  input: GFM

liquid:
  error_mode: strict

collections:
  legacy:
    name: "Legacy (Lua) Docs"
    site_section: true
    output: true
    permalink: /legacy/:path/
    prefix: "/legacy"
    selectorName: "Legacy"
    description: "Documentation for Load Impact Legacy, the Lua based product, in operation since 2011."
    order: 1
  nextgen:
    name: "Next-gen (k6/JS) Docs"
    site_section: true
    output: true
    permalink: /next-gen/:path/
    prefix: "/next-gen"
    selectorName: "Next-gen"
    description: "Get started with Load Impact Next-gen, the successor of what is now referred to as Load Impact Legacy. Run tests in the cloud or on your machine."
    order: 0
  # api:
  #   name: "API Docs"
  #   site_section: true
  #   output: true
  #   permalink: /api/:path/
  #   prefix: "/api"
  #   selectorName: "API"
  #   description: "Reference for the Load Impact API."
  #   order: 2

sass:
  sass_dir: _sass

highlighter: rouge

twitter_username: loadimpact
github_username: loadimpact

defaults:
  -
    scope:
      path: ""
    values:
      hide: false
      search: true

algolia:
  application_id: OW2UD9NPMI
  index_name: staging_li_docs

plugins:
  - jekyll-redirect-from
